# tasks.yaml - futurist_research_crew

futurist_research:
  description: >
    You have these 4 key objectives
    1. Conduct EXTENSIVE research to identify market forces impacting {topic}.
    2. Focus on {specialisation} sources, the current date is {date}.  
    3. Search for content from these sources: {sources}.
    4. Your primary goal is to scan reputable sources to develop a long list of market forces.
    
    Expected research scope - minimum requirements:
    - Minimum of 15 respected {specialisation} publications or thought leaders.
    - At least 15 distinct market forces identified.
    - Minimum of 3 specific examples for each market force.
    - Cover multiple domains.
    - Do not conclude your research until you have gathered a comprehensive set of market forces.
    - Your thoroughness is critical to the success of the overall project.
    - Your research is not complete until you've met or exceeded these minimum requirements.

    Research process:
    1. As part of your research process, you must include the {sources} in your searches.
    2. Identify initial set of market forces from each source.
    3. For each market force, capture the relevant details according to the MarketForce format, then ask yourself: "What related or adjacent market forces might this indicate?"
    4. Expand your list with these adjacent forces.
    5. For any new force identified, repeat steps 3-4.
    6. Continue until you have at least 15 market forces.
    7. Do not include sources over 1 year old, considering the current date is {date}
    
    Remember: Thorough research requires multiple iterations of discovery and expansion.

    Attribution requirements:
    1. For every fact, statistic, quote, example, or finding you include, you MUST provide:
       - The exact URL where the information was found.
       - The specific paragraph or section containing the information, including the exact wording.
       - The name of the source.
    2. Do not paraphrase information - retain key details and numbers as found in the source.
    3. Structure all attributed content according to the AttributedItem format with "content", "source_url", "source_paragraph", and "source_name" fields.

    Research quality:
    1. Compile findings with true and accurate citations and source attributions, ensuring all information is traceable.
    2. **PROVIDE REAL WORKING URLS FOR ALL CONTENT - DO NOT PROVIDE FAKE OR MOCKED CONTENT.**
    3. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES.**
    4. **ALWAYS EXTRACT AND USE THE ACTUAL PUBLICATION DATE FROM THE SOURCE - DO NOT USE TODAY'S DATE.**
    5. **IF A PUBLICATION DATE IS NOT CLEARLY VISIBLE, MAKE A REASONABLE ESTIMATE BASED ON CONTENT OR MARK AS UNKNOWN - NEVER DEFAULT TO TODAY'S DATE.**

    Performance and incentive:
    1. Your performance will be evaluated based on the quantity and quality of market forces identified.
    2. The breadth and accuracy of your sources.
    3. The depth of your analysis (detailed market force descriptions).
    4. The quality and accuracy of your attributions and citations (exact URLs, paragraphs, and sources).
    5. The quantity of market forces identified (aim for 15+).
    6. The diversity of domains covered.
    7. You will be rewarded for meeting or exceeding the minimum requirements.
    8. You will be penalized for not meeting the minimum requirements.
    
    The most valuable insights often come from comprehensive research that goes beyond
    obvious sources and findings. Your goal is to deliver the most accurate, comprehensive and thorough analysis possible.

    Your output MUST be formatted as a valid JSON object following the ResearchOutput schema,
    with each fact, statistic, quote, finding, and example properly attributed using the AttributedItem structure.
    Set the source_category to "{specialisation}" in your response.
  expected_output: >
    A structured list of market forces relating to {topic} from respected {specialisation} sources,with detailed attribution for all claims, facts, statistics, and quotes.
  agent: futurist_researcher

futurist_reporting_task:
  description: >
    Review the context you got and expand each market force into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    The report should be dated {date}. The audience should be experts with deep knowledge about the {topic}.

    Report process:
    1. Do not lose any content from the context, make sure include and where relevant expand on the context create all the required report outputs (e.g. key findings, possible signals, possible structural shifts, implications on future of sector, sources)
    2. **PRESERVE THE ORIGINAL SOURCE DATES FROM THE INPUT - DO NOT REPLACE THEM WITH TODAY'S DATE**

    Report quality:
    1. Ensure all information from the context is comprehensively and accurately included in the report.
    2. Compile content with true and accurate citations and source attributions, ensuring all information is traceable.
    3. **PROVIDE REAL WORKING URLS FOR ALL CONTENT - DO NOT PROVIDE FAKE OR MOCKED CONTENT**  
    4. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES**

    Performace and incentive:
    1. Your performance will be evaluated based on the quantity and quality of your report.

    Your output MUST be formatted as a valid JSON object following the MarketForceReport schema.
  expected_output: >
    A fully fledge reports with all the main topics, each with a full section of information.
  agent: futurist_reporting_analyst
  context: [futurist_research]

futurist_formatting_task:
  description: >
    Format the executive report into a beautiful markdown document without '```'.
    Follow these guidelines:
    1. Use proper markdown headers (#, ##, ###)
    2. Include emojis from the section_emoji field
    3. Format market forces and key findings as bullet points
    4. Add proper spacing and sections breaks
    5. Make implications, signals and structural shifts stand out using blockquotes
    6. Ensure the date is properly formatted
    7. Add a table of contents at the beginning
    8. Use horizontal rules (---) to separate major sections
    9. Add inline citations for each major claim using (Author, Year, URL) format
    10. Include a Sources section at the end with numbered references
    11. Each source should include title, publisher/author, and URL
    12. Link inline citations to the corresponding entry in the Sources section
  expected_output: >
    A beautifully formatted markdown report with proper structure, spacing,
    citations, and visual elements that enhance readability and presentation.
  agent: futurist_formatter
  context: [futurist_research, futurist_reporting_task]

futurist_structure_market_forces:
  description: >
    Convert ALL raw market force findings into structured, standardised market force format.
    
    Expected process:
    - Process ALL raw market forces from the previous research task - Make sure you process all of them
    - For each raw market force:
      1. Generate a unique ID (format: "MF-[source_category]-[number]")
      2. Extract a concise short description from the title
      3. Refine the raw description into a well-structured long description
      4. Standardise examples for clarity and impact
      5. Organise source information consistently
      6. Extract and standardise key terms and entities
    
    Structuring quality requirements:
    1. Ensure consistent terminology across all market forces
    2. Maintain all attribution and source information from raw inputs
    3. Enhance readability without losing substantive information
    4. Remove duplicative content within each market force
    5. Standardise formatting of dates, statistics, and metrics
    6. Make sure you process all of the raw market forces
    
    Contextual awareness:
    1. Consider domain-specific terminology relevant to {topic}
    2. Ensure structured output maintains appropriate professional tone
    3. Preserve industry-specific nuances in the structured format
    
   Your output MUST be formatted as a valid JSON OBJECT with a "market_forces" field containing an ARRAY of StructuredMarketForce objects.
  expected_output: >
    A JSON object containing a "market_forces" array of StructuredMarketForce objects with standardised formatting and enhanced structure.
    The array should contain one object for EACH raw market force from the previous research task.

#this was the old content
    Your output MUST be formatted as a valid JSON array of objects following the StructuredMarketForce schema.
    Each object must include all required fields: id, source_category, short_description, long_description,
    examples, source_name, and optionally source_url, source_date, key_terms, and mentioned_entities.

    expected_output: >
      A JSON array of StructuredMarketForce objects with standardised formatting and enhanced structure
    agent: futurist_market_force_extractor
    context: [futurist_research]