# tasks.yaml - futurist_research_crew

futurist_source_identification:
  description: >
    You have these key objectives for SOURCE IDENTIFICATION:
    1. Identify no less than {minimum_number_of_sources} high-quality sources for researching market forces impacting {topic}.
    2. Focus solely on {specialisation} sources, the current date is {date}.
    3. Include at minimum these sources in your search: {research_sources}.
    4. Your primary goal is to identify reputable sources that will yield valuable market forces.

    Expected source identification scope:
    - Minimum of {minimum_number_of_sources} respected {specialisation} publications or thought leaders.
    - Cover multiple domains relevant to {topic}.
    - Prioritise sources published within the last year, considering the current date is {date}.
    - Your thoroughness at this stage is critical to the success of the overall project.

    Source identification process:
    1. Begin by exploring the {research_sources} specified.
    2. If the user has provided specific points of interest: {specific_points_of_interest}, use them to guide your search.
    3. For each potential source, evaluate:
      - Relevance to {topic}
      - Credibility in the field of {specialisation}
      - Publication date (preferring recent content)
      - Potential for yielding multiple market forces
    4. Use the internet search tool to identify promising sources.
    5. After initial extraction, ask yourself: "What related or adjacent market forces might this indicate?"
    6. Keep track of ALL identified source URLs and basic information.
    7. Do not attempt to extract detailed content from sources at this stage.

    Source quality requirements:
    1. **PROVIDE REAL WORKING URLS FOR ALL SOURCES - DO NOT PROVIDE FAKE OR MOCKED SOURCES**
    2. **VERIFY THAT EACH SOURCE IS ACCESSIBLE AND CONTAINS RELEVANT CONTENT**
    3. **ALWAYS EXTRACT AND USE THE ACTUAL PUBLICATION DATE FROM THE SOURCE - DO NOT USE TODAY'S DATE**
    4. **IF A PUBLICATION DATE IS NOT CLEARLY VISIBLE, MAKE A REASONABLE ESTIMATE BASED ON CONTENT OR MARK AS UNKNOWN**

    Performance and incentive:
    1. Your performance will be evaluated based on the quantity and quality of sources identified.
    2. The breadth and diversity of your sources.
    3. The relevance of sources to {topic} and {specialisation}.
    4. The recency and credibility of your sources.

    Your output MUST be formatted as a valid JSON object following this SourceIdentificationResults schema.

  expected_output: >
    A structured JSON object containing NO LESS THAN {minimum_number_of_sources} high-quality sources
    for researching market forces relating to {topic} from respected {specialisation} sources,
    with each source properly documented with a unique ID, URL, title, publisher, publication date, and relevance details.
  agent: futurist_source_identifier


futurist_market_force_extraction:
  description: >
    Using the URLs from the sources identified in the previous task, conduct EXTENSIVE content extraction to identify market forces relevant to {topic}.
    
    IMPORTANT INSTRUCTIONS FOR ACCESSING URLs:
    1. The output from the previous task (futurist_source_identification) is available to you.
    2. This output contains a 'sources' field, which is a list of sources.
    3. Each source in the list has a 'url' field.
    4. You should extract content from ALL these URLs.
    
    For each URL in the 'sources' array from the previous task output:
      - Use the URL and scrape tool to extract the content.
      - Identify all market forces mentioned in the source.
    
    Expected research extraction scope - minimum requirements:
    - Extract content from ALL source URLs identified in the previous task.
    - Identify as many distinct market forces as possible.
    - Find relevant specific examples for each market force.
    - Do not conclude your extraction until you have gathered a comprehensive set of market forces across all the source URLs provided.
    - Your thoroughness is critical to the success of the overall project.
    - Your research is not complete until you've met or exceeded these minimum requirements.

    Research extraction process:
    1. For each source_url identified in the previous task:
      - Use the URL and scrape tool to extract the content.
      - Identify all market forces mentioned in the source.
    2. For each market force, capture the relevant details according to the RawMarketForce format.
    3. Continue until you have identified all relevant market forces.
    
    Remember: Thorough research requires multiple iterations of discovery and expansion.

    Attribution requirements:
    1. For every fact, statistic, quote, example, or finding you include, you MUST provide:
       - The exact URL where the information was found.
       - The specific paragraph or section containing the information, including the exact wording.
       - The name of the source.
    2. Do not paraphrase information - retain key details and numbers as found in the source.
    3. Structure all attributed content according to the AttributedItem format with "content", "source_url", "source_paragraph", and "source_name" fields.

    Research extraction quality:
    1. Compile findings with true and accurate citations and source attributions, ensuring all information is traceable.
    2. **DO NOT PROVIDE FAKE OR MOCKED CONTENT.**
    3. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES.**
    4. **ALWAYS EXTRACT AND USE THE ACTUAL PUBLICATION DATE FROM THE SOURCE - DO NOT USE TODAY'S DATE.**
    5. **IF A PUBLICATION DATE IS NOT CLEARLY VISIBLE, MAKE A REASONABLE ESTIMATE BASED ON CONTENT OR MARK AS UNKNOWN - NEVER DEFAULT TO TODAY'S DATE.**

    Performance and incentive:
    1. Your performance will be evaluated based on the quantity and quality of market forces identified.
    3. The depth of your analysis (detailed market force descriptions, content, examples, key terms, mentioned entities).
    4. The quality and accuracy of your attributions and citations (exact URLs, paragraphs, and sources).
    
    The most valuable insights often come from comprehensive research that goes beyond
    the obvious. Your goal is to deliver the most accurate, comprehensive and thorough analysis possible.

    Your output MUST be formatted as a valid JSON object following the ResearchOutput schema,
    with each fact, statistic, quote, finding, and example properly attributed using the AttributedItem structure.
    Set the source_category to "{specialisation}" in your response.
  expected_output: >
    A structured list of market forces based on the source URLs provided in the previous task, relating to {topic}, with detailed attribution for all claims, facts, statistics, and quotes.
  agent: futurist_content_extractor
  context: [futurist_source_identification]

futurist_reporting_task:
  description: >
    Review the context you got and expand each market force into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    The report should be dated {date}. The audience should be experts with deep knowledge about the {topic}.

    Report process:
    1. Do not lose any content from the context, make sure include and where relevant expand on the context create all the required report outputs (e.g. key findings, possible signals, possible structural shifts, implications on future of sector, sources)
    2. **PRESERVE THE ORIGINAL SOURCE DATES FROM THE INPUT - DO NOT REPLACE THEM WITH TODAY'S DATE**
    3. Use the URL and scrape tool to extract the content you require.

    Report quality:
    1. Ensure all information from the context is comprehensively and accurately included in the report.
    2. Compile content with true and accurate citations and source attributions, ensuring all information is traceable.
    3. **PROVIDE REAL WORKING URLS FOR ALL CONTENT - DO NOT PROVIDE FAKE OR MOCKED CONTENT**  
    4. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES**

    Performace and incentive:
    1. Your performance will be evaluated based on the quantity and quality of your report.

    Your output MUST be formatted as a valid JSON object following the MarketForceReport schema.
  expected_output: >
    A fully fledge reports with all the main topics, each with a full section of information.
  agent: futurist_reporting_analyst
  context: [futurist_market_force_extraction]

futurist_formatting_task:
  description: >
    Format the executive report into a beautiful markdown document without '```'.
    Follow these guidelines:
    1. Use proper markdown headers (#, ##, ###)
    2. Include emojis from the section_emoji field
    3. Format market forces and key findings as bullet points
    4. Add proper spacing and sections breaks
    5. Make implications, signals and structural shifts stand out using blockquotes
    6. Ensure the date is properly formatted
    7. Add a table of contents at the beginning
    8. Use horizontal rules (---) to separate major sections
    9. Add inline citations for each major claim using (Author, Year, URL) format
    10. Include a Sources section at the end with numbered references
    11. Each source should include title, publisher/author, and URL
    12. Link inline citations to the corresponding entry in the Sources section
  expected_output: >
    A beautifully formatted markdown report with proper structure, spacing,
    citations, and visual elements that enhance readability and presentation.
  agent: futurist_formatter
  context: [futurist_market_force_extraction, futurist_reporting_task]

futurist_structure_market_forces:
  description: >
    Convert ALL raw market force findings into structured, standardised market force format.
    
    Expected process:
    - Process ALL raw market forces from the previous research task - Make sure you process all of them
    - For each raw market force:
      1. Generate a unique ID (format: "MF-[source_category]-[number]")
      2. Extract a concise short description from the title
      3. Refine the raw description into a well-structured long description
      4. Standardise examples for clarity and impact
      5. Organise source information consistently
      6. Extract and standardise key terms and entities
    
    Structuring quality requirements:
    1. Ensure consistent terminology across all market forces
    2. Maintain all attribution and source information from raw inputs
    3. Enhance readability without losing substantive information
    4. Remove duplicative content within each market force
    5. Standardise formatting of dates, statistics, and metrics
    6. Make sure you process all of the raw market forces
    
    Contextual awareness:
    1. Consider domain-specific terminology relevant to {topic}
    2. Ensure structured output maintains appropriate professional tone
    3. Preserve industry-specific nuances in the structured format
    
    Your output MUST be formatted as a valid JSON OBJECT with a "market_forces" field containing an ARRAY of StructuredMarketForce objects.
  expected_output: >
    A JSON object containing a "market_forces" array of StructuredMarketForce objects with standardised formatting and enhanced structure.
    The array should contain one object for EACH raw market force from the previous research task.
  agent: futurist_market_force_extractor
  context: [futurist_market_force_extraction]