futurist_research:
  description: >
    Conduct EXTENSIVE research to identify market forces impacting {topic} focus on futurist and foresight sources, the current date is {date}.
    
    Expected research scope - minimum requirements:
    - Minimum of 15 respected futurist and foresight publications or thought leaders.
    - At least 15 distinct market forces identified.
    - Minimum of 3 specific examples for each market force.
    - Cover multiple domains.
    - Do not conclude your research until you have gathered a comprehensive set of market forces.
    - Your thoroughness is critical to the success of the overall project.
    - Your research is not complete until you've met or exceeded these minimum requirements.

    Research process:
    1. As part of your research process, you must include the {sources_futurists} in your searches.
    2. Identify initial set of market forces from each source.
    3. For each market force, capture the relevenat details according to the MarketForce format, then ask yourself: "What related or adjacent market forces might this indicate?"
    4. Expand your list with these adjacent forces.
    5. For any new force identified, repeat steps 3-4.
    6. Continue until you have at least 15 market forces.
    7. Do not include sources over 1 year old, considering the current date is {date}
    
    Remember: Thorough research requires multiple iterations of discovery and expansion.

    Attribution requirements:
    1. For every fact, statistic, quote, example, or finding you include, you MUST provide:
       - The exact URL where the information was found.
       - The specific paragraph or section containing the information, including the exact wording.
       - The name of the source.
    2. Do not paraphrase information - retain key details and numbers as found in the source.
    3. Structure all attributed content according to the AttributedItem format with "content", "source_url", "source_paragraph", and "source_name" fields.

    Research quality:
    1. Compile findings with true and accurate citations and source attributions, ensuring all information is traceable.
    2. **PROVIDE REAL WORKING URLS FOR ALL CONTENT - DO NOT PROVIDE FAKE OR MOCKED CONTENT.**
    3. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES.**
    4. **ALWAYS EXTRACT AND USE THE ACTUAL PUBLICATION DATE FROM THE SOURCE - DO NOT USE TODAY'S DATE.**
    5. **IF A PUBLICATION DATE IS NOT CLEARLY VISIBLE, MAKE A REASONABLE ESTIMATE BASED ON CONTENT OR MARK AS UNKNOWN - NEVER DEFAULT TO TODAY'S DATE.**

    Performance and incentive:
    1. Your performance will be evaluated based on the quantity and quality of market forces identified.
    2. The breadth and accuracy of your sources.
    3. The depth of your analysis (detailed market force descriptions).
    4. The quality and accuracy of your attributions and citations (exact URLs, paragraphs, and sources).
    5. The quantity of market forces identified (aim for 15+).
    6. The diversity of domains covered.
    7. You will be rewarded for meeting or exceeding the minimum requirements.
    8. You will be penalized for not meeting the minimum requirements.
    
    The most valuable insights often come from comprehensive research that goes beyond
    obvious sources and findings. Your goal is to deliver the most accurate, comprehensive and thorough analysis possible.

    Your output MUST be formatted as a valid JSON object following the ResearchOutput schema,
    with each fact, statistic, quote, finding, and example properly attributed using the AttributedItem structure.
    Set the source_category to "Futurist" in your response.
  expected_output: >
    A structured list of market forces relating to {topic} from respected futurist and foresight sources,with detailed attribution for all claims, facts, statistics, and quotes.
  agent: futurist_researcher

reporting_task:
  description: >
    Review the context you got and expand each market force into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    The report should be dated {date}. The audience should be experts with deep knowledge about the {topic}.

    Report process:
    1. Do not lose any content from the context, make sure include and where relevant expand on the context create all the required report outputs (e.g. key findings, possible signals, possible structural shifts, implications on future of sector, sources)
    2. **PRESERVE THE ORIGINAL SOURCE DATES FROM THE INPUT - DO NOT REPLACE THEM WITH TODAY'S DATE**

    Report quality:
    1. Ensure all information from the context is comprehensively and accurately included in the report.
    2. Compile content with true and accurate citations and source attributions, ensuring all information is traceable.
    3. **PROVIDE REAL WORKING URLS FOR ALL CONTENT - DO NOT PROVIDE FAKE OR MOCKED CONTENT**  
    4. **IF CONTENT CANNOT BE FOUND, INDICATE SO, DO NOT MAKE UP CONTENT OR SOURCES**

    Performace and incentive:
    1. Your performance will be evaluated based on the quantity and quality of your report.

    Your output MUST be formatted as a valid JSON object following the MarketForceReport schema.
  expected_output: >
    A fully fledge reports with all the main topics, each with a full section of information.
  agent: reporting_analyst
  context: [futurist_research]

formatting_task:
  description: >
    Format the executive report into a beautiful markdown document without '```'.
    Follow these guidelines:
    1. Use proper markdown headers (#, ##, ###)
    2. Include emojis from the section_emoji field
    3. Format market forces and key findings as bullet points
    4. Add proper spacing and sections breaks
    5. Make implications, signals and structural shifts stand out using blockquotes
    6. Ensure the date is properly formatted
    7. Add a table of contents at the beginning
    8. Use horizontal rules (---) to separate major sections
    9. Add inline citations for each major claim using (Author, Year, URL) format
    10. Include a Sources section at the end with numbered references
    11. Each source should include title, publisher/author, and URL
    12. Link inline citations to the corresponding entry in the Sources section
  expected_output: >
    A beautifully formatted markdown report with proper structure, spacing,
    citations, and visual elements that enhance readability and presentation.
  agent: formatter
  context: [futurist_research, reporting_task]

# consulting_research:
#   description: >
#     Research and identify market forces from major consulting publications.
    
#     Expected research scope:
#     - Minimum of 5 major consulting firms (e.g., McKinsey, BCG, Deloitte, Accenture, KPMG)
#     - At least 20 distinct market forces identified
#     - At least 2 specific examples for each market force
    
#     Your performance will be evaluated based on:
#     - The breadth of consulting sources covered
#     - The depth of your market force descriptions
#     - The quantity of unique market forces identified (aim for 20+)
#     - The diversity of industries and domains covered
    
#     Your output MUST be formatted as a valid JSON object following the ResearchOutput schema.
#     Set the source_category to "Consulting" in your response.
#   expected_output: >
#     A structured list of market forces from consulting sources
#   agent: consulting_researcher
#   output_file: outputs/consulting_research.json

# patent_research:
#   description: >
#     Research and identify market forces from patent filings.
    
#     Expected research scope:
#     - Multiple patent databases and tech domains
#     - At least 15 distinct technology-driven market forces
#     - Cover emerging technologies across various industries
    
#     Research process:
#     1. Identify initial set of 10 market forces from patent trends
#     2. For each market force, ask yourself: "What related or adjacent market forces might this indicate?"
#     3. Expand your list with these adjacent forces
#     4. Continue until you have at least 15 market forces
    
#     Your output MUST be formatted as a valid JSON object following the ResearchOutput schema.
#     Set the source_category to "Patent" in your response.
#   expected_output: >
#     A structured list of market forces from patent sources
#   agent: patent_researcher
#   output_file: outputs/patent_research.json

# academic_research:
#   description: >
#     Research and identify market forces from academic and scholarly sources.
    
#     Expected research scope:
#     - Multiple academic journals, conferences, and research institutions
#     - At least 15 distinct market forces backed by academic research
#     - Include perspective from various disciplines (economics, technology, sociology, etc.)
    
#     Your output MUST be formatted as a valid JSON object following the ResearchOutput schema.
#     Set the source_category to "Academic" in your response.
#   expected_output: >
#     A structured list of market forces from academic sources
#   agent: academic_researcher
#   output_file: outputs/academic_research.json

# extraction:
#   description: >
#     Process the research data from all source agents.
    
#     Your task is to extract structured market forces with the following fields:
#     - Unique ID (generate this as "MF-[source_category]-[number]")
#     - Short description (based on title)
#     - Long description (refined from raw_description)
#     - Examples (cleaned from raw_examples)
#     - Source details (including category, name, URL)
#     - Key terms and entities
    
#     Ensure you process ALL market forces from the research agents' outputs.
    
#     Your output MUST be formatted as a valid JSON object following the ExtractorOutput schema.
#   expected_output: >
#     A structured JSON database of market forces with all required fields
#   agent: market_force_extractor
#   context:
#     - futurist_research
#     - consulting_research
#     - patent_research
#     - academic_research
#   output_file: outputs/extraction.json

# consolidation:
#   description: >
#     Analyse the structured market forces and identify similar concepts across different sources.
    
#     When you find similar market forces, consolidate them with:
#     - A new consolidated ID
#     - References to the original market force IDs
#     - A canonical description that synthesises the individual descriptions
#     - Combined examples from all sources
#     - List of all source categories that identified this force
    
#     Be thorough in your analysis - identify all potential connections between market forces.
    
#     Your output MUST be formatted as a valid JSON object following the ConsolidatorOutput schema.
#   expected_output: >
#     A consolidated view of market forces with cross-references
#   agent: market_force_consolidator
#   context:
#     - extraction
#   output_file: outputs/consolidation.json